# Site settings
title: ARIA|DNE
description: >ARIA	DNE, 1994-Ever Present Origin. All rights, reserved, from what’s left, reversed.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one





# Handling Reading
exclude: ["README.md", "README.html"]


